exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  MaximumLineLength:
    active: false
  NoWildcardImports:
    active: false

naming:
  MemberNameEqualsClassName:
    ignoreFunction:
      - "main"

style:
  MaxLineLength:
    active: false
  WildcardImport:
    active: false