exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  NoWildcardImports:
    active: false

naming:
  MemberNameEqualsClassName:
    ignoreFunction:
      - "main"

style:
  WildcardImport:
    active: false